<?php

namespace App\Http\Controllers\Admin;

use App\Models\Bank;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class BankController extends Controller
{
    private $banks = array(
        array('name' => 'Al-Barakah Microfinance Bank', 'entry' => 'AL-Barakah Microfinance Bank', 'code' => '090133', 'nip' => '090133'),
        array('name' => 'Al-Barakah Microfinance Bank', 'entry' => 'Al-Barakah Microfinance Bank', 'code' => '090133', 'nip' => '090133'),
        array('name' => 'Ojokoro Microfinance Bank', 'entry' => 'OJOKORO MICROFINANCE BANK', 'code' => '90527', 'nip' => '90527'),
        array('name' => 'Ojokoro Microfinance Bank', 'entry' => 'Ojokoro Microfinance Bank', 'code' => '90527', 'nip' => '90527'),
        array('name' => '9 Payment Service Bank', 'entry' => '9 Payment Service Bank', 'code' => '120001', 'nip' => '120001'),
        array('name' => '9 Payment Service Bank', 'entry' => '9PAYMENT SERVICE BANK', 'code' => '120001', 'nip' => '120001'),
        array('name' => 'AB Microfinance Bank', 'entry' => 'AB MICROFINANCE BANK', 'code' => '090270', 'nip' => '090270'),
        array('name' => 'AB Microfinance Bank', 'entry' => 'AB Microfinance Bank', 'code' => '090270', 'nip' => '090270'),
        array('name' => 'Abbey Mortgage Bank', 'entry' => 'ABBEY MORTGAGE BANK', 'code' => '070010', 'nip' => '070010'),
        array('name' => 'Abbey Mortgage Bank', 'entry' => 'Abbey Mortgage Bank', 'code' => '070010', 'nip' => '070010'),
        array('name' => 'ABU Microfinance Bank', 'entry' => 'ABU Microfinance Bank', 'code' => '090197', 'nip' => '090197'),
        array('name' => 'ABUCOOP MICROFINANCE BANK', 'entry' => 'ABUCOOP MICROFINANCE BANK', 'code' => '090424', 'nip' => '090424'),
        array('name' => 'Access Bank', 'entry' => 'ACCESS BANK', 'code' => '044', 'nip' => '000014'),
        array('name' => 'Access Bank', 'entry' => 'Access Bank', 'code' => '044', 'nip' => '000014'),
        array('name' => 'Access Bank (Diamond)', 'entry' => 'ACCESS BANK DIAMOND', 'code' => '063', 'nip' => '000005'),
        array('name' => 'Access Bank (Diamond)', 'entry' => 'Access Bank (Diamond)', 'code' => '063', 'nip' => '000005'),
        array('name' => 'AccessMobile', 'entry' => 'ACCESSMONEY', 'code' => '100013', 'nip' => '100013'),
        array('name' => 'AccessMobile', 'entry' => 'AccessMobile', 'code' => '100013', 'nip' => '100013'),
        array('name' => 'Accion Microfinance Bank', 'entry' => 'ACCION MICROFINANCE BANK', 'code' => '090134', 'nip' => '090134'),
        array('name' => 'Accion Microfinance Bank', 'entry' => 'Accion Microfinance Bank', 'code' => '090134', 'nip' => '090134'),
        array('name' => 'ADA MICROFINANCE BANK', 'entry' => 'ADA MICROFINANCE BANK', 'code' => '090483', 'nip' => '090483'),
        array('name' => 'Addosser Microfinance Bank', 'entry' => 'ADDOSSER MICROFINANCE BANK', 'code' => '090160', 'nip' => '090160'),
        array('name' => 'Addosser Microfinance Bank', 'entry' => 'Addosser Microfinance Bank', 'code' => '090160', 'nip' => '090160'),
        array('name' => 'AFEMAI MICROFINANCE BANK', 'entry' => 'AFEMAI MICROFINANCE BANK', 'code' => '90518', 'nip' => '90518'),
        array('name' => 'AG Mortgage Bank', 'entry' => 'AG Mortgage Bank', 'code' => '100028', 'nip' => '100028'),
        array('name' => 'AGOSASA MICROFINANCE BANK LTD', 'entry' => 'AGOSASA MICROFINANCE BANK LTD', 'code' => '090371', 'nip' => '090371'),
        array('name' => 'ALAT by WEMA', 'entry' => 'ALAT by WEMA', 'code' => '035A', 'nip' => '035A'),
        array('name' => 'ALERT MICROFINANCE BANK', 'entry' => 'ALERT MICROFINANCE BANK', 'code' => '090297', 'nip' => '090297'),
        array('name' => 'Alpha Kapital Microfinance Bank', 'entry' => 'ALPHA KAPITAL MICROFINANCE BANK', 'code' => '090169', 'nip' => '090169'),
        array('name' => 'Alpha Kapital Microfinance Bank', 'entry' => 'Alpha Kapital Microfinance Bank', 'code' => '090169', 'nip' => '090169'),
        array('name' => 'ALVANA MICROFINANCE BANK', 'entry' => 'ALVANA MICROFINANCE BANK', 'code' => '090489', 'nip' => '090489'),
        array('name' => 'AMJU Unique Microfinance Bank', 'entry' => 'AMJU UNIQUE MICROFINANCE BANK', 'code' => '090180', 'nip' => '090180'),
        array('name' => 'AMJU Unique Microfinance Bank', 'entry' => 'AMJU Unique Microfinance Bank', 'code' => '090180', 'nip' => '090180'),
        array('name' => 'AMML MFB', 'entry' => 'AMML MFB', 'code' => '090116', 'nip' => '090116'),
        array('name' => 'ANCHORAGE MICROFINANCE BANK', 'entry' => 'ANCHORAGE MICROFINANCE BANK', 'code' => '090476', 'nip' => '090476'),
        array('name' => 'APPLE MICROFINANCE BANK', 'entry' => 'APPLE MICROFINANCE BANK', 'code' => '090376', 'nip' => '090376'),
        array('name' => 'ASO Savings and Loans', 'entry' => 'ASO SAVINGS', 'code' => '401', 'nip' => '090001'),
        array('name' => 'ASO Savings and Loans', 'entry' => 'ASO Savings and Loans', 'code' => '401', 'nip' => '090001'),
        array('name' => 'ASO Savings and Loans', 'entry' => 'ASOSavings & Loans', 'code' => '401', 'nip' => '090001'),
        array('name' => 'ASSET MATRIX MICROFINANCE BANK', 'entry' => 'ASSET MATRIX MICROFINANCE BANK', 'code' => '090287', 'nip' => '090287'),
        array('name' => 'Astrapolaris Microfinance Bank', 'entry' => 'ASTRAPOLARIS MICROFINANCE BANK', 'code' => '090172', 'nip' => '090172'),
        array('name' => 'Astrapolaris Microfinance Bank', 'entry' => 'Astrapolaris Microfinance Bank', 'code' => '090172', 'nip' => '090172'),
        array('name' => 'ATBU MICROFINANCE BANK', 'entry' => 'ATBU MICROFINANCE BANK', 'code' => '090451', 'nip' => '090451'),
        array('name' => 'AVUENEGBE MICROFINANCE BANK', 'entry' => 'AVUENEGBE MICROFINANCE BANK', 'code' => '090478', 'nip' => '090478'),
        array('name' => 'Above Only Microfinance Bank', 'entry' => 'Above Only Microfinance Bank', 'code' => '090260', 'nip' => '090260'),
        array('name' => 'Adeyemi College Staff Microfinance Bank', 'entry' => 'Adeyemi College Staff Microfinance Bank', 'code' => '090268', 'nip' => '090268'),
        array('name' => 'Alhayat Microfinance Bank', 'entry' => 'Al-Hayat Microfinance Bank', 'code' => '090277', 'nip' => '090277'),
        array('name' => 'Alhayat Microfinance Bank', 'entry' => 'Alhayat Microfinance Bank', 'code' => '090277', 'nip' => '090277'),
        array('name' => 'Alekun Microfinance Bank', 'entry' => 'Alekun Microfinance Bank', 'code' => '090259', 'nip' => '090259'),
        array('name' => 'Allworkers Microfinance Bank', 'entry' => 'Allworkers Microfinance Bank', 'code' => '090131', 'nip' => '090131'),
        array('name' => 'Apeks Microfinance Bank', 'entry' => 'Apeks Microfinance Bank', 'code' => '090143', 'nip' => '090143'),
        array('name' => 'Assets Microfinance Bank', 'entry' => 'Assets Microfinance Bank', 'code' => '090473', 'nip' => '090473'),
        array('name' => 'Auchi Microfinance Bank', 'entry' => 'Auchi Microfinance Bank', 'code' => '090264', 'nip' => '090264'),
        array('name' => 'Baines Credit Microfinance Bank', 'entry' => 'BAINES CREDIT MICROFINANCE BANK', 'code' => '090188', 'nip' => '090188'),
        array('name' => 'Baines Credit Microfinance Bank', 'entry' => 'Baines Credit Microfinance Bank', 'code' => '090188', 'nip' => '090188'),
        array('name' => 'BALOGUN FULANI', 'entry' => 'BALOGUN FULANI', 'code' => '090181', 'nip' => '090181'),
        array('name' => 'BANEX MICROFINANCE BANK', 'entry' => 'BANEX MICROFINANCE BANK', 'code' => '090425', 'nip' => '090425'),
        array('name' => 'BAYERO UNIVERSITY MICROFINANCE BANK', 'entry' => 'BAYERO UNIVERSITY MICROFINANCE BANK', 'code' => '090316', 'nip' => '090316'),
        array('name' => 'BC Kash Microfinance Bank', 'entry' => 'BC KASH MICROFINANCE BANK', 'code' => '090127', 'nip' => '090127'),
        array('name' => 'BC Kash Microfinance Bank', 'entry' => 'BC Kash Microfinance Bank', 'code' => '090127', 'nip' => '090127'),
        array('name' => 'BENYSTA MICROFINANCE BANK', 'entry' => 'BENYSTA MICROFINANCE BANK', 'code' => '090413', 'nip' => '090413'),
        array('name' => 'BETA/ACCESS YELLO', 'entry' => 'BETA/ACCESS YELLO', 'code' => '100052', 'nip' => '100052'),
        array('name' => 'BIPC MICROFINANCE BANK', 'entry' => 'BIPC MICROFINANCE BANK', 'code' => '090336', 'nip' => '090336'),
        array('name' => 'BOI MICROFINANCE BANK', 'entry' => 'BOI MICROFINANCE BANK', 'code' => '090444', 'nip' => '090444'),
        array('name' => 'BOJI BOJI MICROFINANCE BANK', 'entry' => 'BOJI BOJI MICROFINANCE BANK', 'code' => '90494', 'nip' => '90494'),
        array('name' => 'BONGHE MICROFINANCE BANK', 'entry' => 'BONGHE MICROFINANCE BANK', 'code' => '090319', 'nip' => '090319'),
        array('name' => 'BORGU MICROFINANCE BANK', 'entry' => 'BORGU MICROFINANCE BANK', 'code' => '090395', 'nip' => '090395'),
        array('name' => 'BORSTAL MICROFINANCE BANK', 'entry' => 'BORSTAL MICROFINANCE BANK', 'code' => '090454', 'nip' => '090454'),
        array('name' => 'Bosak Microfinance Bank', 'entry' => 'Bosak Microfinance Bank', 'code' => '104', 'nip' => '090176'),
        array('name' => 'Bosak Microfinance Bank', 'entry' => 'BOSAK', 'code' => '104', 'nip' => '090176'),
        array('name' => 'Bowen Microfinance Bank', 'entry' => 'Bowen Microfinance Bank', 'code' => '50931', 'nip' => '090148'),
        array('name' => 'Bowen Microfinance Bank', 'entry' => 'BOWEN MICROFINANCE BANK', 'code' => '50931', 'nip' => '090148'),
        array('name' => 'Brent Mortgage Bank', 'entry' => 'Brent Mortgage Bank', 'code' => '070015', 'nip' => '070015'),
        array('name' => 'Brent Mortgage Bank', 'entry' => 'BRENT MORTGAGE BANK', 'code' => '070015', 'nip' => '070015'),
        array('name' => 'BRETHREN MICROFINANCE BANK', 'entry' => 'BRETHREN MICROFINANCE BANK', 'code' => '090293', 'nip' => '090293'),
        array('name' => 'BRIDGEWAY MICROFINANCE BANK', 'entry' => 'BRIDGEWAY MICROFINANCE BANK', 'code' => '090393', 'nip' => '090393'),
        array('name' => 'BRIGHTWAY MICROFINANCE BANK', 'entry' => 'BRIGHTWAY MICROFINANCE BANK', 'code' => '090308', 'nip' => '090308'),
        array('name' => 'BUBAYERO MICORFINANCE BANK', 'entry' => 'BUBAYERO MICORFINANCE BANK', 'code' => '90512', 'nip' => '90512'),
        array('name' => 'BUSINESS SUPPORT MICROFINANCE BANK', 'entry' => 'BUSINESS SUPPORT MICROFINANCE BANK', 'code' => '090406', 'nip' => '090406'),
        array('name' => 'Baobab Microfinance Bank', 'entry' => 'Baobab Microfinance Bank', 'code' => '090136', 'nip' => '090136'),
        array('name' => 'Baobab Microfinance Bank', 'entry' => 'Baobab Microfinance Bank', 'code' => '090136', 'nip' => '090136'),
        array('name' => 'Bluewhales Microfinance Bank', 'entry' => 'Bluewhales Microfinance Bank', 'code' => '090431', 'nip' => '090431'),
        array('name' => 'Boctrust Microfinance Bank', 'entry' => 'Boctrust Microfinance Bank', 'code' => '090117', 'nip' => '090117'),
        array('name' => 'CALABAR MICROFINANCE BANK', 'entry' => 'CALABAR MICROFINANCE BANK', 'code' => '090415', 'nip' => '090415'),
        array('name' => 'CAPITALMETRIQ SWIFT MICROFINANCE BANK', 'entry' => 'CAPITALMETRIQ SWIFT MICROFINANCE BANK', 'code' => '090509', 'nip' => '090509'),
        array('name' => 'CAPSTONE MICROFINANCE BANK', 'entry' => 'CAPSTONE MICROFINANCE BANK', 'code' => '090445', 'nip' => '090445'),
        array('name' => 'CASHCONNECT MFB', 'entry' => 'CASHCONNECT MFB', 'code' => '090360', 'nip' => '090360'),
        array('name' => 'CATLAND MICROFINANCE BANK', 'entry' => 'CATLAND MICROFINANCE BANK', 'code' => '090498', 'nip' => '090498'),
        array('name' => 'CBN', 'entry' => 'CBN', 'code' => '000028', 'nip' => '000028'),
        array('name' => 'Cellulant', 'entry' => 'CELLULANT', 'code' => '100005', 'nip' => '100005'),
        array('name' => 'Cellulant', 'entry' => 'Cellulant', 'code' => '100005', 'nip' => '100005'),
        array('name' => 'CEMCS Microfinance Bank', 'entry' => 'CEMCS Microfinance Bank', 'code' => '50823', 'nip' => '090154'),
        array('name' => 'ChamsMobile', 'entry' => 'ChamsMobile', 'code' => '303', 'nip' => '100015'),
        array('name' => 'ChamsMobile', 'entry' => 'CHAMS MOBILE', 'code' => '303', 'nip' => '100015'),
        array('name' => 'CHANELLE MICROFINANCE BANK', 'entry' => 'CHANELLE MICROFINANCE BANK', 'code' => '090397', 'nip' => '090397'),
        array('name' => 'CHANGHAN RTS MICROFINANCE BANK', 'entry' => 'CHANGHAN RTS MICROFINANCE BANK', 'code' => '090470', 'nip' => '090470'),
        array('name' => 'CHEERISH MICROFINANCE BANK', 'entry' => 'CHEERISH MICROFINANCE BANK', 'code' => '090440', 'nip' => '090440'),
        array('name' => 'CHUKWUNENYE MFB', 'entry' => 'CHUKWUNENYE MFB', 'code' => '0909490', 'nip' => '0909490'),
        array('name' => 'CINTRUST MFB', 'entry' => 'CINTRUST MFB', 'code' => '090480', 'nip' => '090480'),
        array('name' => 'CIT Microfinance Bank', 'entry' => 'CIT Microfinance Bank', 'code' => '090144', 'nip' => '090144'),
        array('name' => 'Citi Bank', 'entry' => 'Citi Bank', 'code' => '023', 'nip' => '000009'),
        array('name' => 'Citi Bank', 'entry' => 'Citibank Nigeria', 'code' => '023', 'nip' => '000009'),
        array('name' => 'Citi Bank', 'entry' => 'CITI BANK', 'code' => '023', 'nip' => '000009'),
        array('name' => 'CITIZEN TRUST MFB', 'entry' => 'CITIZEN TRUST MFB', 'code' => '090343', 'nip' => '090343'),
        array('name' => 'CLOVER LEAF MICROFINANCE BANK', 'entry' => 'CLOVER LEAF MICROFINANCE BANK', 'code' => '090511', 'nip' => '090511'),
        array('name' => 'COASTLINE MICROFINANCE BANK', 'entry' => 'COASTLINE MICROFINANCE BANK', 'code' => '090374', 'nip' => '090374'),
        array('name' => 'CONPRO MICROFINANCE BANK', 'entry' => 'CONPRO MICROFINANCE BANK', 'code' => '090380', 'nip' => '090380'),
        array('name' => 'CORESTEP MICROFINANCE BANK', 'entry' => 'CORESTEP MICROFINANCE BANK', 'code' => '090365', 'nip' => '090365'),
        array('name' => 'Covenant Microfinance Bank', 'entry' => 'Covenant MFB', 'code' => '052', 'nip' => '070006'),
        array('name' => 'Covenant Microfinance Bank', 'entry' => 'Covenant Microfinance Bank', 'code' => '052', 'nip' => '070006'),
        array('name' => 'Covenant Microfinance Bank', 'entry' => 'COVENANT MICROFINANCE BANK', 'code' => '052', 'nip' => '070006'),
        array('name' => 'CRESCENT MICROFINANCE BANK', 'entry' => 'CRESCENT MICROFINANCE BANK', 'code' => '090526', 'nip' => '090526'),
        array('name' => 'CROSSRIVER MICROFINANCE BANK', 'entry' => 'CROSSRIVER MICROFINANCE BANK', 'code' => '090429', 'nip' => '090429'),
        array('name' => 'CROWDFORCE NIGERIA LIMITED', 'entry' => 'CROWDFORCE NIGERIA LIMITED', 'code' => '110017', 'nip' => '110017'),
        array('name' => 'CRUTECH MICROFINANCE BANK', 'entry' => 'CRUTECH MICROFINANCE BANK', 'code' => '090414', 'nip' => '090414'),
        array('name' => 'Carbon', 'entry' => 'Carbon', 'code' => '100026', 'nip' => '100026'),
        array('name' => 'Chibueze MFB', 'entry' => 'Chibueze MFB', 'code' => '090416', 'nip' => '090416'),
        array('name' => 'Chikum Microfinance Bank', 'entry' => 'Chikum Microfinance Bank', 'code' => '090141', 'nip' => '090141'),
        array('name' => 'Consumer Microfinance Bank', 'entry' => 'Consumer Microfinance Bank', 'code' => '090130', 'nip' => '090130'),
        array('name' => 'Contec Global Infotech Limited (NowNow)', 'entry' => 'Contec Global Infotech Limited (NowNow)', 'code' => '075', 'nip' => '100032'),
        array('name' => 'Contec Global Infotech Limited (NowNow)', 'entry' => 'NOW NOW', 'code' => '075', 'nip' => '100032'),
        array('name' => 'Contec Global Infotech Limited (NowNow)', 'entry' => 'NOWNOW', 'code' => '075', 'nip' => '100032'),
        array('name' => 'Coop Mortgage Bank', 'entry' => 'Coop Mortgage Bank', 'code' => '070021', 'nip' => '070021'),
        array('name' => 'Coronation Merchant Bank', 'entry' => 'Coronation Merchant Bank', 'code' => '060001', 'nip' => '060001'),
        array('name' => 'Credit Afrique Microfinance Bank', 'entry' => 'Credit Afrique Microfinance Bank', 'code' => '090159', 'nip' => '090159'),
        array('name' => 'DAVODANI MICROFINANCE BANK', 'entry' => 'DAVODANI MICROFINANCE BANK', 'code' => '090391', 'nip' => '090391'),
        array('name' => 'Daylight Microfinance Bank', 'entry' => 'DAYLIGHT MICROFINANCE BANK', 'code' => '090167', 'nip' => '090167'),
        array('name' => 'Daylight Microfinance Bank', 'entry' => 'Daylight Microfinance Bank', 'code' => '090167', 'nip' => '090167'),
        array('name' => 'Delta Trust Mortage Bank', 'entry' => 'Delta Trust Mortage Bank', 'code' => '70023', 'nip' => '70023'),
        array('name' => 'eTranzact', 'entry' => 'eTranzact', 'code' => '100006', 'nip' => '100006'),
        array('name' => 'eTranzact', 'entry' => 'E-TRANZACT', 'code' => '100006', 'nip' => '100006'),
        array('name' => 'EAGLE FLIGHT MICROFINANCE BANK', 'entry' => 'EAGLE FLIGHT MICROFINANCE BANK', 'code' => '090294', 'nip' => '090294'),
        array('name' => 'Eartholeum', 'entry' => 'Eartholeum', 'code' => '100021', 'nip' => '100021'),
        array('name' => 'Eartholeum', 'entry' => 'EARTHOLEUM', 'code' => '100021', 'nip' => '100021'),
        array('name' => 'EBSU MICROFINANCE BANK', 'entry' => 'EBSU MICROFINANCE BANK', 'code' => '090427', 'nip' => '090427'),
        array('name' => 'Ecobank Nigeria', 'entry' => 'Ecobank Nigeria', 'code' => '050', 'nip' => '000010'),
        array('name' => 'Ecobank Nigeria', 'entry' => 'EcoBank PLC', 'code' => '050', 'nip' => '000010'),
        array('name' => 'Ecobank Nigeria', 'entry' => 'ECOBANK', 'code' => '050', 'nip' => '000010'),
        array('name' => 'Ecobank Xpress Account', 'entry' => 'Ecobank Xpress Account', 'code' => '100008', 'nip' => '100008'),
        array('name' => 'Ecobank Xpress Account', 'entry' => 'ECOBANK XPRESS ACCOUNT', 'code' => '100008', 'nip' => '100008'),
        array('name' => 'EDFIN MICROFINANCE BANK', 'entry' => 'EDFIN MICROFINANCE BANK', 'code' => '090310', 'nip' => '090310'),
        array('name' => 'EK-RELIABLE MFB', 'entry' => 'EK-RELIABLE MFB', 'code' => '090389', 'nip' => '090389'),
        array('name' => 'Ekondo Microfinance Bank', 'entry' => 'Ekondo MFB', 'code' => '562', 'nip' => '090097'),
        array('name' => 'Ekondo Microfinance Bank', 'entry' => 'Ekondo Microfinance Bank', 'code' => '562', 'nip' => '090097'),
        array('name' => 'Ekondo Microfinance Bank', 'entry' => 'EKONDO MICROFINANCE BANK', 'code' => '562', 'nip' => '090097'),
        array('name' => 'Empire trust MFB', 'entry' => 'Empire trust MFB', 'code' => '090114', 'nip' => '090114'),
        array('name' => 'Empire trust MFB', 'entry' => 'EMPIRE TRUST MICROFINANCE BANK', 'code' => '090114', 'nip' => '090114'),
        array('name' => 'Esan Microfinance Bank', 'entry' => 'Esan Microfinance Bank', 'code' => '090189', 'nip' => '090189'),
        array('name' => 'Esan Microfinance Bank', 'entry' => 'ESAN MICROFINANCE BANK', 'code' => '090189', 'nip' => '090189'),
        array('name' => 'Eso-E Microfinance Bank', 'entry' => 'Eso-E Microfinance Bank', 'code' => '090166', 'nip' => '090166'),
        array('name' => 'Eso-E Microfinance Bank', 'entry' => 'ESO-E MICROFINANCE BANK', 'code' => '090166', 'nip' => '090166'),
        array('name' => 'EVANGEL MICROFINANCE BANK', 'entry' => 'EVANGEL MICROFINANCE BANK', 'code' => '090304', 'nip' => '090304'),
        array('name' => 'EVERGREEN MICROFINANCE BANK', 'entry' => 'EVERGREEN MICROFINANCE BANK', 'code' => '090332', 'nip' => '090332'),
        array('name' => 'Eyowo MFB', 'entry' => 'Eyowo', 'code' => '50126', 'nip' => '090328'),
        array('name' => 'Eyowo MFB', 'entry' => 'Eyowo MFB', 'code' => '50126', 'nip' => '090328'),
        array('name' => 'Eyowo MFB', 'entry' => 'EYOWO(USSD)', 'code' => '50126', 'nip' => '090328'),
        array('name' => 'EcoMobile', 'entry' => 'EcoMobile', 'code' => '100030', 'nip' => '100030'),
        array('name' => 'Emeralds Microfinance Bank', 'entry' => 'Emeralds Microfinance Bank', 'code' => '090273', 'nip' => '090273'),
        array('name' => 'Enterprise Bank', 'entry' => 'Enterprise Bank', 'code' => '000019', 'nip' => '000019'),
        array('name' => 'FAME MICROFINANCE BANK', 'entry' => 'FAME MICROFINANCE BANK', 'code' => '090330', 'nip' => '090330'),
        array('name' => 'FAST Microfinance Bank', 'entry' => 'FAST MICROFINANCE BANK', 'code' => '090179', 'nip' => '090179'),
        array('name' => 'FAST Microfinance Bank', 'entry' => 'FAST Microfinance Bank', 'code' => '090179', 'nip' => '090179'),
        array('name' => 'FBN Mortgages Limited', 'entry' => 'FBN Mortgages Limited', 'code' => '090107', 'nip' => '090107'),
        array('name' => 'FIRSTMONIE', 'entry' => 'FIRSTMONIE', 'code' => '100014', 'nip' => '100014'),
        array('name' => 'FIRSTMONIE', 'entry' => 'FBNMobile', 'code' => '100014', 'nip' => '100014'),
        array('name' => 'FBNQuest Merchant Bank', 'entry' => 'FBNQUEST Merchant Bank', 'code' => '060002', 'nip' => '060002'),
        array('name' => 'FBNQuest Merchant Bank', 'entry' => 'FBNQuest Merchant Bank', 'code' => '060002', 'nip' => '060002'),
        array('name' => 'First City Monument Bank', 'entry' => 'First City Monument Bank', 'code' => '214', 'nip' => '000003'),
        array('name' => 'First City Monument Bank', 'entry' => 'FCMB', 'code' => '214', 'nip' => '000003'),
        array('name' => 'FCMB Easy Account', 'entry' => 'FCMB Easy Account', 'code' => '100031', 'nip' => '100031'),
        array('name' => 'FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK', 'entry' => 'FEDERAL POLYTECHNIC NEKEDE MICROFINANCE BANK', 'code' => '090398', 'nip' => '090398'),
        array('name' => 'FEDETH MICROFINANCE BANK', 'entry' => 'FEDETH MICROFINANCE BANK', 'code' => '090482', 'nip' => '090482'),
        array('name' => 'FETS', 'entry' => 'FET', 'code' => '003', 'nip' => '100001'),
        array('name' => 'FETS', 'entry' => 'FETS', 'code' => '003', 'nip' => '100001'),
        array('name' => 'FEWCHORE FINANCE COMPANY LIMITED', 'entry' => 'FEWCHORE FINANCE COMPANY LIMITED', 'code' => '50002', 'nip' => '50002'),
        array('name' => 'FFS Microfinance Bank', 'entry' => 'FFS MICROFINANCE BANK', 'code' => '090153', 'nip' => '090153'),
        array('name' => 'FFS Microfinance Bank', 'entry' => 'FFS Microfinance Bank', 'code' => '090153', 'nip' => '090153'),
        array('name' => 'Fidelity Bank', 'entry' => 'Fidelity Bank', 'code' => '070', 'nip' => '000007'),
        array('name' => 'Fidelity Bank', 'entry' => 'FIDELITY BANK', 'code' => '070', 'nip' => '000007'),
        array('name' => 'Fidelity Mobile', 'entry' => 'Fidelity Mobile', 'code' => '100019', 'nip' => '100019'),
        array('name' => 'Fidelity Mobile', 'entry' => 'FIDELITY MOBILE', 'code' => '100019', 'nip' => '100019'),
        array('name' => 'FIMS MICROFINANCE BANK', 'entry' => 'FIMS MICROFINANCE BANK', 'code' => '90507', 'nip' => '90507'),
        array('name' => 'FINATRUST MICROFINANCE BANK', 'entry' => 'FINATRUST MICROFINANCE BANK', 'code' => '090111', 'nip' => '090111'),
        array('name' => 'FINCA MICROFINANCE BANK', 'entry' => 'FINCA MICROFINANCE BANK', 'code' => '090400', 'nip' => '090400'),
        array('name' => 'FIRMUS MICROFINANCE BANK', 'entry' => 'Firmus MFB', 'code' => '090366', 'nip' => '090366'),
        array('name' => 'FIRMUS MICROFINANCE BANK', 'entry' => 'FIRMUS MICROFINANCE BANK', 'code' => '090366', 'nip' => '090366'),
        array('name' => 'First Bank PLC', 'entry' => 'First Bank PLC', 'code' => '011', 'nip' => '000016'),
        array('name' => 'First Bank PLC', 'entry' => 'First Bank of Nigeria', 'code' => '011', 'nip' => '000016'),
        array('name' => 'First Bank PLC', 'entry' => 'FIRST BANK OF NIGERIA', 'code' => '011', 'nip' => '000016'),
        array('name' => 'FIRST HERITAGE MFB', 'entry' => 'FIRST HERITAGE MFB', 'code' => '090479', 'nip' => '090479'),
        array('name' => 'FIRST TRUST MORTGAGE BANK PLC', 'entry' => 'FIRST TRUST MORTGAGE BANK PLC', 'code' => '090107', 'nip' => '090107'),
        array('name' => 'FORESIGHT MICROFINANCE BANK', 'entry' => 'FORESIGHT MICROFINANCE BANK', 'code' => '090521', 'nip' => '090521'),
        array('name' => 'Fortis Microfinance Bank', 'entry' => 'Fortis Microfinance Bank', 'code' => '070002', 'nip' => '070002'),
        array('name' => 'Fortis Microfinance Bank', 'entry' => 'FORTIS MFB', 'code' => '070002', 'nip' => '070002'),
        array('name' => 'FORTIS MOBILE', 'entry' => 'FortisMobile', 'code' => '100016', 'nip' => '100016'),
        array('name' => 'FORTIS MOBILE', 'entry' => 'FORTIS MOBILE', 'code' => '100016', 'nip' => '100016'),
        array('name' => 'FORTRESS MICROFINANCE BANK', 'entry' => 'FORTRESS MICROFINANCE BANK', 'code' => '090486', 'nip' => '090486'),
        array('name' => 'FSDH Merchant Bank', 'entry' => 'FSDH MERCHANT BANK LIMIT', 'code' => '501', 'nip' => '400001'),
        array('name' => 'FSDH Merchant Bank', 'entry' => 'FSDH Merchant Bank', 'code' => '501', 'nip' => '400001'),
        array('name' => 'FSDH Merchant Bank', 'entry' => 'FSDH Merchant Bank Limited', 'code' => '501', 'nip' => '400001'),
        array('name' => 'FUTMINNA MICROFINANCE BANK', 'entry' => 'FUTMINNA MICROFINANCE BANK', 'code' => '090438', 'nip' => '090438'),
        array('name' => 'Futo Microfinance Bank', 'entry' => 'Futo Microfinance Bank', 'code' => '090158', 'nip' => '090158'),
        array('name' => 'Futo Microfinance Bank', 'entry' => 'FUTO MICROFINANCE BANK', 'code' => '090158', 'nip' => '090158'),
        array('name' => 'Federal University Dutse Microfinance Bank', 'entry' => 'Federal University Dutse Microfinance Bank', 'code' => '090318', 'nip' => '090318'),
        array('name' => 'Fidfund Microfinance Bank', 'entry' => 'Fidfund Microfinance Bank', 'code' => '090126', 'nip' => '090126'),
        array('name' => 'First Generation Mortgage Bank', 'entry' => 'First Generation Mortgage Bank', 'code' => '070014', 'nip' => '070014'),
        array('name' => 'First Royal Microfinance Bank', 'entry' => 'First Royal Microfinance Bank', 'code' => '090164', 'nip' => '090164'),
        array('name' => 'Flutterwave Technology Solutions Limited', 'entry' => 'Flutterwave Technology Solutions Limited', 'code' => '110002', 'nip' => '110002'),
        array('name' => 'Fullrange Microfinance Bank', 'entry' => 'Fullrange Microfinance Bank', 'code' => '090145', 'nip' => '090145'),
        array('name' => 'GAINT STRIDE MFB', 'entry' => 'GAINT STRIDE MFB', 'code' => '090475', 'nip' => '090475'),
        array('name' => 'GARKI MICROFINANCE BANK', 'entry' => 'GARKI MICROFINANCE BANK', 'code' => '090484', 'nip' => '090484'),
        array('name' => 'Gateway Mortgage Bank', 'entry' => 'Gateway Mortgage Bank', 'code' => '070009', 'nip' => '070009'),
        array('name' => 'Gateway Mortgage Bank', 'entry' => 'GATEWAY MORTGAGE', 'code' => '070009', 'nip' => '070009'),
        array('name' => 'GIGINYA MICROFINANCE BANK', 'entry' => 'GIGINYA MICROFINANCE BANK', 'code' => '090411', 'nip' => '090411'),
        array('name' => 'GIREI MICROFINANCE BANK', 'entry' => 'GIREI MICROFINANCE BANK', 'code' => '090186', 'nip' => '090186'),
        array('name' => 'GIWA MICROFINANCE BANK', 'entry' => 'GIWA MICROFINANCE BANK', 'code' => '090441', 'nip' => '090441'),
        array('name' => 'Globus Bank', 'entry' => 'Globus Bank', 'code' => '00103', 'nip' => '000027'),
        array('name' => 'Globus Bank', 'entry' => 'GLOBUS BANK', 'code' => '00103', 'nip' => '000027'),
        array('name' => 'GMB MICROFINANCE BANK', 'entry' => 'GMB MICROFINANCE BANK', 'code' => '090408', 'nip' => '090408'),
        array('name' => 'GoMoney', 'entry' => 'GoMoney', 'code' => '100022', 'nip' => '100022'),
        array('name' => 'GoMoney', 'entry' => 'GOMONEY', 'code' => '100022', 'nip' => '100022'),
        array('name' => 'GOOD NEIGHBORS MFB', 'entry' => 'GOOD NEIGHBORS MFB', 'code' => '090467', 'nip' => '090467'),
        array('name' => 'GOODNEWS MICROFINANCE BANK', 'entry' => 'GOODNEWS MICROFINANCE BANK', 'code' => '090495', 'nip' => '090495'),
        array('name' => 'Greenwich Merchant Bank', 'entry' => 'Greenwich Merchant Bank', 'code' => '060004', 'nip' => '060004'),
        array('name' => 'Greenwich Merchant Bank', 'entry' => 'GREENWICH MERCHANT BANK', 'code' => '060004', 'nip' => '060004'),
        array('name' => 'GTMobile', 'entry' => 'GTBank MOBILE MONEY', 'code' => '100009', 'nip' => '100009'),
        array('name' => 'GTMobile', 'entry' => 'GTMobile', 'code' => '100009', 'nip' => '100009'),
        array('name' => 'GTI MICROFINANCE BANK', 'entry' => 'GTI MICROFINANCE BANK', 'code' => '090385', 'nip' => '090385'),
        array('name' => 'Guaranty Trust Bank', 'entry' => 'Guaranty Trust Bank', 'code' => '058', 'nip' => '000013'),
        array('name' => 'Guaranty Trust Bank', 'entry' => 'GUARANTY TRUST BANK', 'code' => '058', 'nip' => '000013'),
        array('name' => 'Gashua Microfinance Bank', 'entry' => 'Gashua Microfinance Bank', 'code' => '090168', 'nip' => '090168'),
        array('name' => 'Gowans Microfinance Bank', 'entry' => 'Gowans Microfinance Bank', 'code' => '090122', 'nip' => '090122'),
        array('name' => 'GreenBank Microfinance Bank', 'entry' => 'GreenBank Microfinance Bank', 'code' => '090178', 'nip' => '090178'),
        array('name' => 'Greenville Microfinance Bank', 'entry' => 'Greenville Microfinance Bank', 'code' => '090269', 'nip' => '090269'),
        array('name' => 'Grooming Microfinance Bank', 'entry' => 'Grooming Microfinance Bank', 'code' => '090195', 'nip' => '090195'),
        array('name' => 'Hackman Microfinance Bank', 'entry' => 'Hackman Microfinance Bank', 'code' => '51251', 'nip' => '090147'),
        array('name' => 'Hackman Microfinance Bank', 'entry' => 'HACKMAN MICROFINANCE BANK', 'code' => '51251', 'nip' => '090147'),
        array('name' => 'Haggai Mortgage Bank Limited', 'entry' => 'Haggai Mortgage Bank Limited', 'code' => '070017', 'nip' => '070017'),
        array('name' => 'Haggai Mortgage Bank Limited', 'entry' => 'HAGGAI MORTGAGE BANK', 'code' => '070017', 'nip' => '070017'),
        array('name' => 'Hasal Microfinance Bank', 'entry' => 'Hasal Microfinance Bank', 'code' => '50383', 'nip' => '090121'),
        array('name' => 'Hasal Microfinance Bank', 'entry' => 'HASAL MICROFINANCE BANK', 'code' => '50383', 'nip' => '090121'),
        array('name' => 'HEADWAY MICROFINANCE BANK', 'entry' => 'HEADWAY MICROFINANCE BANK', 'code' => '090363', 'nip' => '090363'),
        array('name' => 'Hedonmark', 'entry' => 'Hedonmark', 'code' => '100017', 'nip' => '100017'),
        array('name' => 'Hedonmark', 'entry' => 'HEDONMARK MOBILE', 'code' => '100017', 'nip' => '100017'),
        array('name' => 'Heritage Bank', 'entry' => 'Heritage Bank', 'code' => '030', 'nip' => '000020'),
        array('name' => 'Heritage Bank', 'entry' => 'HERITAGE BANK', 'code' => '030', 'nip' => '000020'),
        array('name' => 'HOMEBASE MORTGAGE BANK', 'entry' => 'HOMEBASE MORTGAGE BANK', 'code' => '070024', 'nip' => '070024'),
        array('name' => 'HOPE PAYMENT SERVICE BANK', 'entry' => 'HOPE PAYMENT SERVICE BANK', 'code' => '120002', 'nip' => '120002'),
        array('name' => 'HighStreet Microfinance Bank', 'entry' => 'HighStreet Microfinance Bank', 'code' => '090175', 'nip' => '090175'),
        array('name' => 'Highland Microfinance Bank', 'entry' => 'Highland Microfinance Bank', 'code' => '090418', 'nip' => '090418'),
        array('name' => 'IBETO MICROFINANCE BANK', 'entry' => 'IBETO MICROFINANCE BANK', 'code' => '090439', 'nip' => '090439'),
        array('name' => 'IBILE Microfinance Bank', 'entry' => 'IBILE MICROFINANCE BANK', 'code' => '090118', 'nip' => '090118'),
        array('name' => 'IBILE Microfinance Bank', 'entry' => 'IBILE Microfinance Bank', 'code' => '090118', 'nip' => '090118'),
        array('name' => 'IBOM FADAMA MICROFINANCE BANK', 'entry' => 'IBOM FADAMA MICROFINANCE BANK', 'code' => '090519', 'nip' => '090519'),
        array('name' => 'IC GLOBAL MICROFINANCE BANK', 'entry' => 'IC GLOBAL MICROFINANCE BANK', 'code' => '090520', 'nip' => '090520'),
        array('name' => 'IKENNE MICROFINANCE BANK', 'entry' => 'IKENNE MICROFINANCE BANK', 'code' => '090324', 'nip' => '090324'),
        array('name' => 'IKIRE MICROFINANCE BANK', 'entry' => 'IKIRE MICROFINANCE BANK', 'code' => '090279', 'nip' => '090279'),
        array('name' => 'ILISAN MICROFINANCE BANK', 'entry' => 'ILISAN MICROFINANCE BANK', 'code' => '090370', 'nip' => '090370'),
        array('name' => 'ILORA MICROFINANCE BANK', 'entry' => 'ILORA MICROFINANCE BANK', 'code' => '090430', 'nip' => '090430'),
        array('name' => 'ILORIN MICROFINANCE BANK', 'entry' => 'ILORIN MICROFINANCE BANK', 'code' => '090350', 'nip' => '090350'),
        array('name' => 'IMOWO MICROFINANCE BANK', 'entry' => 'IMOWO MICROFINANCE BANK', 'code' => '090417', 'nip' => '090417'),
        array('name' => 'Imperial Homes Mortgage Bank', 'entry' => 'Imperial Homes Mortgage Bank', 'code' => '100024', 'nip' => '100024'),
        array('name' => 'Imperial Homes Mortgage Bank', 'entry' => 'IMPERIAL HOMES MORTGAGE BANK', 'code' => '100024', 'nip' => '100024'),
        array('name' => 'INFINITY MICROFINANCE BANK', 'entry' => 'INFINITY MICROFINANCE BANK', 'code' => '090157', 'nip' => '090157'),
        array('name' => 'INSIGHT MICROFINANCE BANK', 'entry' => 'INSIGHT MICROFINANCE BANK', 'code' => '090434', 'nip' => '090434'),
        array('name' => 'INTERLAND MFB', 'entry' => 'INTERLAND MFB', 'code' => '090386', 'nip' => '090386'),
        array('name' => 'IPERU MFB', 'entry' => 'IPERU MFB', 'code' => '090493', 'nip' => '090493'),
        array('name' => 'IRL Microfinance Bank', 'entry' => 'IRL Microfinance Bank', 'code' => '090149', 'nip' => '090149'),
        array('name' => 'ISALEOYO MFB', 'entry' => 'ISALEOYO MFB', 'code' => '090377', 'nip' => '090377'),
        array('name' => 'ISALEOYO MICROFINANCE BANK', 'entry' => 'ISALEOYO MICROFINANCE BANK', 'code' => '090392', 'nip' => '090392'),
        array('name' => 'ISHIE MICROFINANCE BANK', 'entry' => 'ISHIE MICROFINANCE BANK', 'code' => '090428', 'nip' => '090428'),
        array('name' => 'Imo State Microfinance Bank', 'entry' => 'Imo State Microfinance Bank', 'code' => '090258', 'nip' => '090258'),
        array('name' => 'Infinity Trust Mortgage Bank', 'entry' => 'Infinity Trust Mortgage Bank', 'code' => '070016', 'nip' => '070016'),
        array('name' => 'Innovectives Kesh', 'entry' => 'Innovectives Kesh', 'code' => '100029', 'nip' => '100029'),
        array('name' => 'Intellifin', 'entry' => 'Intellifin', 'code' => '100027', 'nip' => '100027'),
        array('name' => 'Intellifin', 'entry' => 'MIMONEY (POWERED BY INTELLIFIN)', 'code' => '100027', 'nip' => '100027'),
        array('name' => 'Izon Microfinance Bank', 'entry' => 'Izon Microfinance Bank', 'code' => '090421', 'nip' => '090421'), 
        array('name' => 'Jaiz Bank', 'entry' => 'Jaiz Bank', 'code' => '301', 'nip' => '000006'),
        array('name' => 'Jaiz Bank', 'entry' => 'JAIZ BANK', 'code' => '301', 'nip' => '000006'),
        array('name' => 'JESSEFIELD MICROFINANCE BANK', 'entry' => 'JESSEFIELD MICROFINANCE BANK', 'code' => '090352', 'nip' => '090352'),
        array('name' => 'Jubilee-Life Mortgage Bank', 'entry' => 'JUBILEE-LIFE MORTAGE BANK', 'code' => '090003', 'nip' => '090003'),
        array('name' => 'Jubilee-Life Mortgage Bank', 'entry' => 'Jubilee-Life Mortgage Bank', 'code' => '090003', 'nip' => '090003'), 
        array('name' => 'KCMB Microfinance Bank', 'entry' => 'KCMB Microfinance Bank', 'code' => '090191', 'nip' => '090191'),
        array('name' => 'Keystone Bank', 'entry' => 'Keystone Bank', 'code' => '082', 'nip' => '000002'),
        array('name' => 'Keystone Bank', 'entry' => 'KEYSTONE BANK', 'code' => '082', 'nip' => '000002'),
        array('name' => 'KINGDOM COLLEGE MICROFINANCE BANK', 'entry' => 'KINGDOM COLLEGE MICROFINANCE BANK', 'code' => '090487', 'nip' => '090487'),
        array('name' => 'KONTAGORA MICROFINANCE BANK', 'entry' => 'KONTAGORA MICROFINANCE BANK', 'code' => '090299', 'nip' => '090299'),
        array('name' => 'Kuda Bank', 'entry' => 'Kuda', 'code' => '50211', 'nip' => '090267'),
        array('name' => 'Kuda Bank', 'entry' => 'Kuda Bank', 'code' => '50211', 'nip' => '090267'),
        array('name' => 'Kuda Bank', 'entry' => 'KUDA MICROFINANCE BANK', 'code' => '50211', 'nip' => '090267'),
        array('name' => 'KWASU MICROFINANCE BANK', 'entry' => 'KWASU MICROFINANCE BANK', 'code' => '090450', 'nip' => '090450'),
        array('name' => 'Kegow', 'entry' => 'Kegow', 'code' => '100015', 'nip' => '100036'),
        array('name' => 'La Fayette Microfinance Bank', 'entry' => 'La Fayette Microfinance Bank', 'code' => '090155', 'nip' => '090155'),
        array('name' => 'La Fayette Microfinance Bank', 'entry' => 'LA FAYETTE MICROFINANCE BANK', 'code' => '090155', 'nip' => '090155'),
        array('name' => 'Lagos Building Investment Company', 'entry' => 'Lagos Building Investment Company', 'code' => '90052', 'nip' => '070012'),
        array('name' => 'Lagos Building Investment Company', 'entry' => 'Lagos Building Investment Company Plc.', 'code' => '90052', 'nip' => '070012'),
        array('name' => 'Lagos Building Investment Company', 'entry' => 'LAGOS BUILDING INVESTMENT COMPANY', 'code' => '90052', 'nip' => '070012'),
        array('name' => 'LANDGOLD MICROFINANCE BANK', 'entry' => 'LANDGOLD MICROFINANCE BANK', 'code' => '090422', 'nip' => '090422'),
        array('name' => 'Lapo Microfinance Bank', 'entry' => 'Lapo Microfinance Bank', 'code' => '090177', 'nip' => '090177'),
        array('name' => 'Lapo Microfinance Bank', 'entry' => 'LAPO MFB', 'code' => '090177', 'nip' => '090177'),
        array('name' => 'Lavender Microfinance Bank', 'entry' => 'Lavender Microfinance Bank', 'code' => '090271', 'nip' => '090271'),
        array('name' => 'Lavender Microfinance Bank', 'entry' => 'LAVENDER MFB', 'code' => '090271', 'nip' => '090271'),
        array('name' => 'LEGEND MICROFINANCE BANK', 'entry' => 'LEGEND MICROFINANCE BANK', 'code' => '090372', 'nip' => '090372'),
        array('name' => 'LINKS MICROFINANCE BANK', 'entry' => 'LINKS MICROFINANCE BANK', 'code' => '090435', 'nip' => '090435'),
        array('name' => 'LIVINGTRUST MORTGAGE BANK PLC', 'entry' => 'LIVINGTRUST MORTGAGE BANK PLC', 'code' => '070007', 'nip' => '070007'),
        array('name' => 'LOTUS BANK', 'entry' => 'LOTUS BANK', 'code' => '000029', 'nip' => '000029'),
        array('name' => 'Lovonus Microfinance Bank', 'entry' => 'Lovonus Microfinance Bank', 'code' => '090265', 'nip' => '090265'),
        array('name' => 'Lovonus Microfinance Bank', 'entry' => 'LOVONUS MICROFINANCE BANK', 'code' => '090265', 'nip' => '090265'),
        array('name' => 'Letshego Microfinance Bank', 'entry' => 'Letshego MFB', 'code' => '090420', 'nip' => '090420'),
        array('name' => 'Letshego Microfinance Bank', 'entry' => 'Letshego Microfinance Bank', 'code' => '090420', 'nip' => '090420'),
        array('name' => 'M36', 'entry' => 'M36', 'code' => '100035', 'nip' => '100035'),
        array('name' => 'Malachy Microfinance Bank', 'entry' => 'Malachy Microfinance Bank', 'code' => '090174', 'nip' => '090174'),
        array('name' => 'Malachy Microfinance Bank', 'entry' => 'MALACHY MICROFINANCE BANK', 'code' => '090174', 'nip' => '090174'),
        array('name' => 'Manny Microfinance bank', 'entry' => 'Manny Microfinance bank', 'code' => '090383', 'nip' => '090383'),
        array('name' => 'Manny Microfinance bank', 'entry' => 'MANNY MICROFINANCE BANK', 'code' => '090383', 'nip' => '090383'),
        array('name' => 'MARITIME MICROFINANCE BANK', 'entry' => 'MARITIME MICROFINANCE BANK', 'code' => '090410', 'nip' => '090410'),
        array('name' => 'MAUTECH Microfinance Bank', 'entry' => 'MAUTECH MICROFINANCE BANK', 'code' => '090423', 'nip' => '090423'),
        array('name' => 'MAUTECH Microfinance Bank', 'entry' => 'MAUTECH Microfinance Bank', 'code' => '090423', 'nip' => '090423'),
        array('name' => 'MAYFAIR MICROFINANCE BANK', 'entry' => 'MAYFAIR MICROFINANCE BANK', 'code' => '090321', 'nip' => '090321'),
        array('name' => 'MEGAPRAISE MICROFINANCE BANK', 'entry' => 'MEGAPRAISE MICROFINANCE BANK', 'code' => '090280', 'nip' => '090280'),
        array('name' => 'MEMPHIS MICROFINANCE BANK', 'entry' => 'MEMPHIS MICROFINANCE BANK', 'code' => '090432', 'nip' => '090432'),
        array('name' => 'MICROVIS MICRO FINANCE BANK', 'entry' => 'MICROVIS MICRO FINANCE BANK', 'code' => '090113', 'nip' => '090113'),
        array('name' => 'Midland Microfinance Bank', 'entry' => 'Midland Microfinance Bank', 'code' => '090192', 'nip' => '090192'),
        array('name' => 'Midland Microfinance Bank', 'entry' => 'MIDLAND MICROFINANCE BANK', 'code' => '090192', 'nip' => '090192'),
        array('name' => 'MIMO (Mkudi)', 'entry' => 'Mkudi', 'code' => '100011', 'nip' => '100011'),
        array('name' => 'MIMO (Mkudi)', 'entry' => 'MIMO (Mkudi)', 'code' => '100011', 'nip' => '100011'),
        array('name' => 'Mint-Finex MICROFINANCE BANK', 'entry' => 'Mint-Finex MICROFINANCE BANK', 'code' => '090281', 'nip' => '090281'),
        array('name' => 'Mint-Finex MICROFINANCE BANK', 'entry' => 'MINT-FINEX MFB', 'code' => '090281', 'nip' => '090281'),
        array('name' => 'MOLUSI MICROFINANCE BANK', 'entry' => 'MOLUSI MICROFINANCE BANK', 'code' => '090362', 'nip' => '090362'),
        array('name' => 'MONARCH MICROFINANCE BANK', 'entry' => 'MONARCH MICROFINANCE BANK', 'code' => '090462', 'nip' => '090462'),
        array('name' => 'MoneyBox', 'entry' => 'MoneyBox', 'code' => '100020', 'nip' => '100020'),
        array('name' => 'MoneyBox', 'entry' => 'MONEY BOX', 'code' => '100020', 'nip' => '100020'),
        array('name' => 'Money Trust Microfinance Bank', 'entry' => 'Money Trust Microfinance Bank', 'code' => '090129', 'nip' => '090129'),
        array('name' => 'Money Trust Microfinance Bank', 'entry' => 'MONEY TRUST MICROFINANCE BANK', 'code' => '090129', 'nip' => '090129'),
        array('name' => 'MONIEPOINT MICROFINANCE BANK', 'entry' => 'MONIEPOINT MICROFINANCE BANK', 'code' => '090405', 'nip' => '090405'),
        array('name' => 'MOYOFADE MICROFINANCE BANK', 'entry' => 'MOYOFADE MICROFINANCE BANK', 'code' => '090448', 'nip' => '090448'),
        array('name' => 'Mutual Benefits Microfinance Bank', 'entry' => 'Mutual Benefits', 'code' => '107', 'nip' => '090190'),
        array('name' => 'Mutual Benefits Microfinance Bank', 'entry' => 'Mutual Benefits Microfinance Bank', 'code' => '107', 'nip' => '090190'),
        array('name' => 'Mutual Benefits Microfinance Bank', 'entry' => 'MUTUAL BENEFITS MICROFINANCE BANK', 'code' => '107', 'nip' => '090190'),
        array('name' => 'Mutual Trust Microfinance Bank', 'entry' => 'Mutual Trust Microfinance Bank', 'code' => '090151', 'nip' => '090151'),
        array('name' => 'Mutual Trust Microfinance Bank', 'entry' => 'MUTUAL TRUST MICROFINANCE BANK', 'code' => '090151', 'nip' => '090151'),
        array('name' => 'Mainstreet Microfinance Bank', 'entry' => 'Mainstreet Microfinance Bank', 'code' => '090171', 'nip' => '090171'),
        array('name' => 'Momo Payment Service Bank', 'entry' => 'Momo Payment Service Bank', 'code' => '120003', 'nip' => '120003'),
        array('name' => 'Moneymaster PSB', 'entry' => 'Moneymaster PSB', 'code' => '120005', 'nip' => '120005'),
        array('name' => 'Ndiorah Microfinance Bank', 'entry' => 'Ndiorah Microfinance Bank', 'code' => '090128', 'nip' => '090128'),
        array('name' => 'Ndiorah Microfinance Bank', 'entry' => 'NDIORAH MICROFINANCE BANK', 'code' => '090128', 'nip' => '090128'),
        array('name' => 'NEPTUNE MICROFINANCE BANK', 'entry' => 'NEPTUNE MICROFINANCE BANK', 'code' => '090329', 'nip' => '090329'),
        array('name' => 'New Dawn Microfinance Bank', 'entry' => 'New Dawn Microfinance Bank', 'code' => '090205', 'nip' => '090205'),
        array('name' => 'New Dawn Microfinance Bank', 'entry' => 'NEW DAWN MICROFINANCE BANK', 'code' => '090205', 'nip' => '090205'),
        array('name' => 'NEW GOLDEN PASTURES MICROFINANCE BANK', 'entry' => 'NEW GOLDEN PASTURES MICROFINANCE BANK', 'code' => '090378', 'nip' => '090378'),
        array('name' => 'NICE MICROFINANCE BANK', 'entry' => 'NICE MICROFINANCE BANK', 'code' => '090459', 'nip' => '090459'),
        array('name' => 'NIGERIAN NAVY MICROFINANCE BANK', 'entry' => 'Navy Microfinance Bank', 'code' => '090263', 'nip' => '090263'),
        array('name' => 'NIGERIAN NAVY MICROFINANCE BANK', 'entry' => 'NIGERIAN NAVY MICROFINANCE BANK', 'code' => '090263', 'nip' => '090263'),
        array('name' => 'NIP Virtual Bank', 'entry' => 'NIP Virtual Bank', 'code' => '999999', 'nip' => '999999'),
        array('name' => 'NIRSAL Microfinance Bank', 'entry' => 'NIRSAL MICROFINANCE BANK', 'code' => '090194', 'nip' => '090194'),
        array('name' => 'NIRSAL Microfinance Bank', 'entry' => 'NIRSAL Microfinance Bank', 'code' => '090194', 'nip' => '090194'),
        array('name' => 'NNEW WOMEN MICROFINANCE BANK', 'entry' => 'NNEW WOMEN MICROFINANCE BANK', 'code' => '090283', 'nip' => '090283'),
        array('name' => 'Nova Merchant Bank', 'entry' => 'NOVA', 'code' => '105', 'nip' => '060003'),
        array('name' => 'Nova Merchant Bank', 'entry' => 'NOVA Merchant Bank', 'code' => '105', 'nip' => '060003'),
        array('name' => 'Nova Merchant Bank', 'entry' => 'Nova Merchant Bank', 'code' => '105', 'nip' => '060003'),
        array('name' => 'NPF MicroFinance Bank', 'entry' => 'NPF', 'code' => '002', 'nip' => '070001'),
        array('name' => 'NPF MicroFinance Bank', 'entry' => 'NPF MICROFINANCE BANK PLC', 'code' => '002', 'nip' => '070001'),
        array('name' => 'NPF MicroFinance Bank', 'entry' => 'NPF MicroFinance Bank', 'code' => '002', 'nip' => '070001'),
        array('name' => 'NSUK MICROFINANCE BANK', 'entry' => 'NSUK MICROFINANCE BANK', 'code' => '090491', 'nip' => '090491'),
        array('name' => 'NUMO MICROFINANCE BANK', 'entry' => 'NUMO MICROFINANCE BANK', 'code' => '090516', 'nip' => '090516'),
        array('name' => 'NUTURE MICROFINANCE BANK', 'entry' => 'NUTURE MICROFINANCE BANK', 'code' => '090364', 'nip' => '090364'),
        array('name' => 'NWANNEGADI MICROFINANCE BANK', 'entry' => 'NWANNEGADI MICROFINANCE BANK', 'code' => '090399', 'nip' => '090399'),
        array('name' => 'Nagarta Microfinance Bank', 'entry' => 'Nagarta Microfinance Bank', 'code' => '090152', 'nip' => '090152'),
        array('name' => 'New Prudential Bank', 'entry' => 'New Prudential Bank', 'code' => '090108', 'nip' => '090108'),
        array('name' => 'Nigeria Prison Microfinance Bank', 'entry' => 'Nigeria Prison Microfinance Bank', 'code' => '090505', 'nip' => '090505'),
        array('name' => 'OAKLAND MICROFINACE BANK', 'entry' => 'OAKLAND MICROFINACE BANK', 'code' => '090437', 'nip' => '090437'),
        array('name' => 'OCHE MICROFINANCE BANK', 'entry' => 'OCHE MICROFINANCE BANK', 'code' => '090333', 'nip' => '090333'),
        array('name' => 'OLOFIN OWENA MICROFINANCE BANK', 'entry' => 'OLOFIN OWENA MICROFINANCE BANK', 'code' => '090468', 'nip' => '090468'),
        array('name' => 'OLOWOLAGBA MICROFINANCE BANK', 'entry' => 'OLOWOLAGBA MICROFINANCE BANK', 'code' => '090404', 'nip' => '090404'),
        array('name' => 'OMIYE MICROFINANCE BANK', 'entry' => 'OMIYE MICROFINANCE BANK', 'code' => '090295', 'nip' => '090295'),
        array('name' => 'One Finance', 'entry' => 'ONE FINANCE', 'code' => '100026', 'nip' => '100026'),
        array('name' => 'One Finance', 'entry' => 'One Finance', 'code' => '100026', 'nip' => '100026'),
        array('name' => 'Olabisi Onabanjo University Microfinance Bank', 'entry' => 'Olabisi Onabanjo University Microfinance Bank', 'code' => '090272', 'nip' => '090272'),
        array('name' => 'Olabisi Onabanjo University Microfinance Bank', 'entry' => 'OOU MICROFINANCE BANK', 'code' => '090272', 'nip' => '090272'),
        array('name' => 'Opay Digital Services/Paycom', 'entry' => 'Paycom', 'code' => '305', 'nip' => '100004'),
        array('name' => 'Opay Digital Services/Paycom', 'entry' => 'Opay/Paycom', 'code' => '305', 'nip' => '100004'),
        array('name' => 'Opay Digital Services/Paycom', 'entry' => 'OPAY DIGITAL SERVICES LIMITED', 'code' => '305', 'nip' => '100004'),
        array('name' => 'ORAUKWU MICROFINANCE BANK', 'entry' => 'ORAUKWU MICROFINANCE BANK', 'code' => '090492', 'nip' => '090492'),
        array('name' => 'ORITABASORUN MICROFINANCE BANK', 'entry' => 'ORITABASORUN MICROFINANCE BANK', 'code' => '090460', 'nip' => '090460'),
        array('name' => 'OSCOTECH MICROFINANCE BANK', 'entry' => 'OSCOTECH MICROFINANCE BANK', 'code' => '090396', 'nip' => '090396'),
        array('name' => 'OSPOLY MICROFINANCE BANK', 'entry' => 'OSPOLY MICROFINANCE BANK', 'code' => '090456', 'nip' => '090456'),
        array('name' => 'Ohafia Microfinance Bank', 'entry' => 'Ohafia Microfinance Bank', 'code' => '090119', 'nip' => '090119'),
        array('name' => 'Okpoga Microfinance Bank', 'entry' => 'Okpoga Microfinance Bank', 'code' => '090161', 'nip' => '090161'),
        array('name' => 'Oluchukwu Microfinance Bank', 'entry' => 'Oluchukwu Microfinance Bank', 'code' => '090471', 'nip' => '090471'),
        array('name' => 'Omoluabi savings and loans', 'entry' => 'Omoluabi savings and loans', 'code' => '070007', 'nip' => '070007'),
        array('name' => 'Paga', 'entry' => 'Paga', 'code' => '009', 'nip' => '100002'),
        array('name' => 'Paga', 'entry' => 'PagaTech', 'code' => '009', 'nip' => '100002'),
        array('name' => 'Paga', 'entry' => 'PAGA', 'code' => '009', 'nip' => '100002'),
        array('name' => 'Page Financials', 'entry' => 'Page Financials', 'code' => '070008', 'nip' => '070008'),
        array('name' => 'Page Financials', 'entry' => 'PAGE FINANCIALS', 'code' => '070008', 'nip' => '070008'),
        array('name' => 'PALMCOAST MICROFINANCE BANK', 'entry' => 'PALMCOAST MICROFINANCE BANK', 'code' => '090497', 'nip' => '090497'),
        array('name' => 'PALMPAY', 'entry' => 'PALMPAY', 'code' => '100033', 'nip' => '100033'),
        array('name' => 'Parralex Microfinance bank', 'entry' => 'Parralex Microfinance bank', 'code' => '090004', 'nip' => '090004'),
        array('name' => 'Parallex Bank', 'entry' => 'Parallex Bank', 'code' => '015', 'nip' => '000030'),
        array('name' => 'Parallex Bank', 'entry' => 'Parallex MFB', 'code' => '015', 'nip' => '000030'),
        array('name' => 'Parallex Bank', 'entry' => 'PARALLEX BANK', 'code' => '015', 'nip' => '000030'),
        array('name' => 'Parkway-ReadyCash', 'entry' => 'PARKWAY', 'code' => '311', 'nip' => '100003'),
        array('name' => 'Parkway-ReadyCash', 'entry' => 'Parkway - ReadyCash', 'code' => '311', 'nip' => '100003'),
        array('name' => 'Parkway-ReadyCash', 'entry' => 'Parkway-ReadyCash', 'code' => '311', 'nip' => '100003'),
        array('name' => 'PARKWAY MICROFINANCE BANK', 'entry' => 'PARKWAY MICROFINANCE BANK', 'code' => '090390', 'nip' => '090390'),
        array('name' => 'PatrickGold Microfinance Bank', 'entry' => 'PATRICKGOLD MICROFINANCE BANK', 'code' => '090317', 'nip' => '090317'),
        array('name' => 'PatrickGold Microfinance Bank', 'entry' => 'PatrickGold Microfinance Bank', 'code' => '090317', 'nip' => '090317'),
        array('name' => 'PayAttitude Online', 'entry' => 'PayAttitude Online', 'code' => '110001', 'nip' => '110001'),
        array('name' => 'PayAttitude Online', 'entry' => 'PAYATTITUDE ONLINE', 'code' => '110001', 'nip' => '110001'),
        array('name' => 'PEACE MICROFINANCE BANK', 'entry' => 'PEACE MICROFINANCE BANK', 'code' => '090402', 'nip' => '090402'),
        array('name' => 'PecanTrust Microfinance Bank', 'entry' => 'PecanTrust Microfinance Bank', 'code' => '090137', 'nip' => '090137'),
        array('name' => 'PecanTrust Microfinance Bank', 'entry' => 'PECANTRUST MICROFINANCE BANK', 'code' => '090137', 'nip' => '090137'),
        array('name' => 'Pennywise Microfinance Bank', 'entry' => 'PENNYWISE MFB', 'code' => '090196', 'nip' => '090196'),
        array('name' => 'Pennywise Microfinance Bank', 'entry' => 'Pennywise Microfinance Bank', 'code' => '090196', 'nip' => '090196'),
        array('name' => 'Personal Trust Microfinance Bank', 'entry' => 'Personal Trust Microfinance Bank', 'code' => '090135', 'nip' => '090135'),
        array('name' => 'Personal Trust Microfinance Bank', 'entry' => 'PERSONAL TRUST', 'code' => '090135', 'nip' => '090135'),
        array('name' => 'Polaris Bank', 'entry' => 'Polaris Bank', 'code' => '076', 'nip' => '000008'),
        array('name' => 'Polaris Bank', 'entry' => 'Polaris bank', 'code' => '076', 'nip' => '000008'),
        array('name' => 'Polaris Bank', 'entry' => 'POLARIS BANK LTD', 'code' => '076', 'nip' => '000008'),
        array('name' => 'PremiumTrust Bank', 'entry' => 'PremiumTrust Bank', 'code' => '000031', 'nip' => '000031'),
        array('name' => 'PremiumTrust Bank', 'entry' => 'PREMIUMTRUST BANK', 'code' => '000031', 'nip' => '000031'),
        array('name' => 'PRISCO MICROFINANCE BANK', 'entry' => 'PRISCO MICROFINANCE BANK', 'code' => '090481', 'nip' => '090481'),
        array('name' => 'PRISTINE DIVITIS MICROFINANCE BANK', 'entry' => 'PRISTINE DIVITIS MICROFINANCE BANK', 'code' => '090490', 'nip' => '090490'),
        array('name' => 'PROJECTS MICROFINANCE BANK', 'entry' => 'PROJECTS MICROFINANCE BANK', 'code' => '090503', 'nip' => '090503'),
        array('name' => 'Providus Bank', 'entry' => 'PROVIDUS BANK', 'code' => '101', 'nip' => '000023'),
        array('name' => 'Providus Bank', 'entry' => 'Providus Bank', 'code' => '101', 'nip' => '000023'),
        array('name' => 'Providus Bank', 'entry' => 'ProvidusBank PLC', 'code' => '101', 'nip' => '000023'),
        array('name' => 'PURPLEMONEY MICROFINANCE BANK', 'entry' => 'PURPLEMONEY MICROFINANCE BANK', 'code' => '090303', 'nip' => '090303'),
        array('name' => 'Petra Microfinance Bank', 'entry' => 'Petra Microfinance Bank', 'code' => '090165', 'nip' => '090165'),
        array('name' => 'Platinum Mortgage Bank', 'entry' => 'Platinum Mortgage Bank', 'code' => '070013', 'nip' => '070013'),
        array('name' => 'Preeminent Microfinance Bank', 'entry' => 'Preeminent Microfinance Bank', 'code' => '090412', 'nip' => '090412'),
        array('name' => 'Prestige Microfinance Bank', 'entry' => 'Prestige Microfinance Bank', 'code' => '090274', 'nip' => '090274'),
        array('name' => 'Quickfund Microfinance Bank', 'entry' => 'Quickfund Microfinance Bank', 'code' => '090261', 'nip' => '090261'),
        array('name' => 'RAHAMA MICROFINANCE BANK', 'entry' => 'RAHAMA MICROFINANCE BANK', 'code' => '090170', 'nip' => '090170'),
        array('name' => 'Refuge Mortgage Bank', 'entry' => 'Refuge Mortgage Bank', 'code' => '070011', 'nip' => '070011'),
        array('name' => 'Refuge Mortgage Bank', 'entry' => 'REFUGE MORTGAGE BANK', 'code' => '070011', 'nip' => '070011'),
        array('name' => 'REHOBOTH MICROFINANCE BANK', 'entry' => 'REHOBOTH MICROFINANCE BANK', 'code' => '090463', 'nip' => '090463'),
        array('name' => 'Reliance Microfinance Bank', 'entry' => 'Reliance Microfinance Bank', 'code' => '090173', 'nip' => '090173'),
        array('name' => 'Reliance Microfinance Bank', 'entry' => 'RELIANCE MICROFINANCE BANK', 'code' => '090173', 'nip' => '090173'),
        array('name' => 'RenMoney Microfinance Bank', 'entry' => 'RenMoney Microfinance Bank', 'code' => '90198', 'nip' => '90198'),
        array('name' => 'RenMoney Microfinance Bank', 'entry' => 'RENMONEY', 'code' => '90198', 'nip' => '90198'),
        array('name' => 'REPHIDIM MICROFINANCE BANK', 'entry' => 'REPHIDIM MICROFINANCE BANK', 'code' => '090322', 'nip' => '090322'),
        array('name' => 'RIGO MICROFINANCE BANK', 'entry' => 'RIGO MICROFINANCE BANK', 'code' => '090433', 'nip' => '090433'),
        array('name' => 'RIMA MICROFINANCE BANK', 'entry' => 'RIMA MICROFINANCE BANK', 'code' => '090443', 'nip' => '090443'),
        array('name' => 'RIMA GROWTH PATHWAY MICROFINANCE BANK', 'entry' => 'RIMA GROWTH PATHWAY MICROFINANCE BANK', 'code' => '090515', 'nip' => '090515'),
        array('name' => 'Rubies Microfinance Bank', 'entry' => 'Rubies MFB', 'code' => '125', 'nip' => '090175'),
        array('name' => 'Rubies Microfinance Bank', 'entry' => 'Rubies Microfinance Bank', 'code' => '125', 'nip' => '090175'),
        array('name' => 'Rubies Microfinance Bank', 'entry' => 'RUBIES MICROFINANCE BANK', 'code' => '125', 'nip' => '090175'),
        array('name' => 'Rand merchant Bank', 'entry' => 'Rand merchant Bank', 'code' => '502', 'nip' => '502'),
        array('name' => 'Regent Microfinance Bank', 'entry' => 'Regent Microfinance Bank', 'code' => '090125', 'nip' => '090125'),
        array('name' => 'Richway Microfinance Bank', 'entry' => 'Richway Microfinance Bank', 'code' => '090132', 'nip' => '090132'),
        array('name' => 'Royal Exchange Microfinance Bank', 'entry' => 'Royal Exchange Microfinance Bank', 'code' => '090138', 'nip' => '090138'),
        array('name' => 'SAFEGATE MICROFINANCE BANK', 'entry' => 'SAFEGATE MICROFINANCE BANK', 'code' => '090485', 'nip' => '090485'),
        array('name' => 'SAFETRUST MORTGAGE BANK LIMITED', 'entry' => 'SafeTrust', 'code' => '090006', 'nip' => '090006'),
        array('name' => 'SAFETRUST MORTGAGE BANK LIMITED', 'entry' => 'SAFETRUST MORTGAGE BANK LIMITED', 'code' => '090006', 'nip' => '090006'),
        array('name' => 'Sagamu Microfinance Bank', 'entry' => 'Sagamu Microfinance Bank', 'code' => '090140', 'nip' => '090140'),
        array('name' => 'Sagamu Microfinance Bank', 'entry' => 'SAGAMU MICROFINANCE BANK', 'code' => '090140', 'nip' => '090140'),
        array('name' => 'Seed Capital Microfinance Bank', 'entry' => 'Seed Capital Microfinance Bank', 'code' => '090112', 'nip' => '090112'),
        array('name' => 'Seed Capital Microfinance Bank', 'entry' => 'SEED CAPITAL MICROFINANCE BANK', 'code' => '090112', 'nip' => '090112'),
        array('name' => 'SEEDVEST MICROFINANCE BANK', 'entry' => 'SEEDVEST MICROFINANCE BANK', 'code' => '090369', 'nip' => '090369'),
        array('name' => 'SHALOM MICROFINANCE BANK', 'entry' => 'SHALOM MICROFINANCE BANK', 'code' => '090502', 'nip' => '090502'),
        array('name' => 'SLS MICROFINANCE BANK', 'entry' => 'SLS MICROFINANCE BANK', 'code' => '090449', 'nip' => '090449'),
        array('name' => 'SOLID ALLIANZE MICROFINANCE BANK', 'entry' => 'SOLID ALLIANZE MICROFINANCE BANK', 'code' => '090506', 'nip' => '090506'),
        array('name' => 'SOLIDROCK MICROFINANCE BANK', 'entry' => 'SOLIDROCK MICROFINANCE BANK', 'code' => '090524', 'nip' => '090524'),
        array('name' => 'Sparkle Microfinance Bank', 'entry' => 'Sparkle Microfinance Bank', 'code' => '51310', 'nip' => '090325'),
        array('name' => 'Sparkle Microfinance Bank', 'entry' => 'Sparkle', 'code' => '51310', 'nip' => '090325'),
        array('name' => 'Sparkle Microfinance Bank', 'entry' => 'SPARKLE', 'code' => '51310', 'nip' => '090325'),
        array('name' => 'SPECTRUM MICROFINANCE BANK', 'entry' => 'SPECTRUM MICROFINANCE BANK', 'code' => '090436', 'nip' => '090436'),
        array('name' => 'Stanbic Ease Wallet', 'entry' => 'Stanbic IBTC @ease wallet', 'code' => '100007', 'nip' => '100007'),
        array('name' => 'Stanbic Ease Wallet', 'entry' => 'STANBIC IBTC @ EASE WALLET', 'code' => '100007', 'nip' => '100007'),
        array('name' => 'Stanbic IBTC Bank', 'entry' => 'Stanbic IBTC Bank', 'code' => '221', 'nip' => '000012'),
        array('name' => 'Stanbic IBTC Bank', 'entry' => 'STANBIC IBTC BANK', 'code' => '221', 'nip' => '000012'),
        array('name' => 'Standard Chartered Bank', 'entry' => 'Standard Chartered Bank', 'code' => '068', 'nip' => '000021'),
        array('name' => 'Standard Chartered Bank', 'entry' => 'Standard Chaterted bank PLC', 'code' => '068', 'nip' => '000021'),
        array('name' => 'Standard Chartered Bank', 'entry' => 'STANDARD CHARTERED BANK NIGERIA LTD', 'code' => '068', 'nip' => '000021'),
        array('name' => 'STB MORTGAGE BANK', 'entry' => 'STB MORTGAGE BANK', 'code' => '070022', 'nip' => '070022'),
        array('name' => 'Sterling Bank', 'entry' => 'Sterling Bank', 'code' => '232', 'nip' => '000001'),
        array('name' => 'Sterling Bank', 'entry' => 'Sterling Bank PLC', 'code' => '232', 'nip' => '000001'),
        array('name' => 'Sterling Bank', 'entry' => 'STERLING BANK', 'code' => '232', 'nip' => '000001'),
        array('name' => 'STOCKCORP MICROFINANCE BANK', 'entry' => 'STOCKCORP MICROFINANCE BANK', 'code' => '090340', 'nip' => '090340'),
        array('name' => 'SULSPAP MICROFINANCE BANK', 'entry' => 'SULSPAP MICROFINANCE BANK', 'code' => '090305', 'nip' => '090305'),
        array('name' => 'SUNBEAM MFB', 'entry' => 'SUNBEAM MFB', 'code' => '090302', 'nip' => '090302'),
        array('name' => 'Suntrust Bank', 'entry' => 'Suntrust Bank', 'code' => '100', 'nip' => '000022'),
        array('name' => 'Suntrust Bank', 'entry' => 'SUNTRUST BANK NIGERIA LIMITED', 'code' => '100', 'nip' => '000022'),
        array('name' => 'SUPPORT MICROFINANCE BANK', 'entry' => 'SUPPORT MICROFINANCE BANK', 'code' => '090446', 'nip' => '090446'),
        array('name' => 'Safe Haven MFB', 'entry' => 'Safe Haven MFB', 'code' => '090286', 'nip' => '090286'),
        array('name' => 'Seap Microfinance Bank', 'entry' => 'Seap Microfinance Bank', 'code' => '090513', 'nip' => '090513'),
        array('name' => 'SmartCash Payment Service Bank', 'entry' => 'SmartCash Payment Service Bank', 'code' => '120004', 'nip' => '120004'),
        array('name' => 'Standard Microfinance Bank', 'entry' => 'Standard Microfinance Bank', 'code' => '090182', 'nip' => '090182'),
        array('name' => 'Stellas Microfinance Bank', 'entry' => 'Stellas MFB limited', 'code' => '090262', 'nip' => '090262'),
        array('name' => 'Stellas Microfinance Bank', 'entry' => 'Stellas Microfinance Bank', 'code' => '090262', 'nip' => '090262'),
        array('name' => 'TAJ Bank', 'entry' => 'TAJ BANK', 'code' => '302', 'nip' => '000026'),
        array('name' => 'TAJ Bank', 'entry' => 'TAJ Bank', 'code' => '302', 'nip' => '000026'),
        array('name' => 'TAJ Bank', 'entry' => 'Taj Bank Limited', 'code' => '302', 'nip' => '000026'),
        array('name' => 'TAJ_PINSPAY', 'entry' => 'TAJ_PINSPAY', 'code' => '080002', 'nip' => '080002'),
        array('name' => 'Tangerine Bank', 'entry' => 'Tangerine Bank', 'code' => '090426', 'nip' => '090426'),
        array('name' => 'Tangerine Bank', 'entry' => 'TANGERINE MONEY', 'code' => '090426', 'nip' => '090426'),
        array('name' => 'TCF MFB', 'entry' => 'TCF MFB', 'code' => '51211', 'nip' => '090115'),
        array('name' => 'TeasyMobile', 'entry' => 'Teasy', 'code' => '004', 'nip' => '100010'),
        array('name' => 'TeasyMobile', 'entry' => 'TeasyMobile', 'code' => '004', 'nip' => '100010'),
        array('name' => 'TeasyMobile', 'entry' => 'TEASY MOBILE', 'code' => '004', 'nip' => '100010'),
        array('name' => 'THINK FINANCE MICROFINANCE BANK', 'entry' => 'THINK FINANCE MICROFINANCE BANK', 'code' => '090373', 'nip' => '090373'),
        array('name' => 'TRUST MICROFINANCE BANK', 'entry' => 'TRUST MICROFINANCE BANK', 'code' => '090327', 'nip' => '090327'),
        array('name' => 'TagPay', 'entry' => 'TagPay', 'code' => '100023', 'nip' => '100023'),
        array('name' => 'Titan Trust Bank', 'entry' => 'Titan Bank', 'code' => '102', 'nip' => '000025'),
        array('name' => 'Titan Trust Bank', 'entry' => 'Titan Trust Bank', 'code' => '102', 'nip' => '000025'),
        array('name' => 'Titan Trust Bank', 'entry' => 'Titan Trust Bank Ltd', 'code' => '102', 'nip' => '000025'),
        array('name' => 'Trident Microfinance Bank', 'entry' => 'Trident Microfinance Bank', 'code' => '090146', 'nip' => '090146'),
        array('name' => 'TrustBanc J6 MFB', 'entry' => 'TrustBanc J6 MFB', 'code' => '090123', 'nip' => '090123'),
        array('name' => 'Trustbond Mortgage Bank', 'entry' => 'Trustbond', 'code' => '018', 'nip' => '090005'),
        array('name' => 'Trustbond Mortgage Bank', 'entry' => 'Trustbond Mortgage Bank', 'code' => '018', 'nip' => '090005'),
        array('name' => 'Trustfund Microfinance Bank', 'entry' => 'Trustfund Microfinance Bank', 'code' => '090276', 'nip' => '090276'),
        array('name' => 'U & C MICROFINANCE BANK', 'entry' => 'U & C MICROFINANCE BANK', 'code' => '090315', 'nip' => '090315'),
        array('name' => 'UMUNNACHI MICROFINANCE BANK', 'entry' => 'UMUNNACHI MICROFINANCE BANK', 'code' => '090510', 'nip' => '090510'),
        array('name' => 'UNAAB MICROFINANCE BANK', 'entry' => 'UNAAB MICROFINANCE BANK', 'code' => '090331', 'nip' => '090331'),
        array('name' => 'UNIBADAN MICROFINANCE BANK', 'entry' => 'UNIBADAN MICROFINANCE BANK', 'code' => '090461', 'nip' => '090461'),
        array('name' => 'UNIILORIN MICROFINANCE BANK', 'entry' => 'UNIILORIN MICROFINANCE BANK', 'code' => '090341', 'nip' => '090341'),
        array('name' => 'UNILAG MICROFINANCE BANK', 'entry' => 'UNILAG MICROFINANCE BANK', 'code' => '090452', 'nip' => '090452'),
        array('name' => 'Union Bank PLC', 'entry' => 'UNION BANK', 'code' => '032', 'nip' => '000018'),
        array('name' => 'Union Bank PLC', 'entry' => 'Union Bank PLC', 'code' => '032', 'nip' => '000018'),
        array('name' => 'Union Bank PLC', 'entry' => 'Union Bank of Nigeria', 'code' => '032', 'nip' => '000018'),
        array('name' => 'United Bank For Africa', 'entry' => 'United Bank For Africa', 'code' => '033', 'nip' => '000004'),
        array('name' => 'United Bank For Africa', 'entry' => 'United Bank for Africa', 'code' => '033', 'nip' => '000004'),
        array('name' => 'United Bank For Africa', 'entry' => 'UNITED BANK FOR AFRICA', 'code' => '033', 'nip' => '000004'),
        array('name' => 'Unity Bank', 'entry' => 'Unity Bank', 'code' => '215', 'nip' => '000011'),
        array('name' => 'Unity Bank', 'entry' => 'Unity Bank PLC', 'code' => '215', 'nip' => '000011'),
        array('name' => 'Unity Bank', 'entry' => 'UNITY BANK', 'code' => '215', 'nip' => '000011'),
        array('name' => 'UNIUYO Microfinance Bank', 'entry' => 'UNIUYO Microfinance Bank', 'code' => '090338', 'nip' => '090338'),
        array('name' => 'UNN MFB', 'entry' => 'UNN MFB', 'code' => '090251', 'nip' => '090251'),
        array('name' => 'Uhuru Microfinance Bank', 'entry' => 'Uhuru Microfinance Bank', 'code' => '090517', 'nip' => '090517'),
        array('name' => 'Uniben Microfinance Bank', 'entry' => 'Uniben Microfinance Bank', 'code' => '090266', 'nip' => '090266'),
        array('name' => 'Unical Microfinance Bank', 'entry' => 'Unical Microfinance Bank', 'code' => '090193', 'nip' => '090193'),
        array('name' => 'VERDANT MICROFINANCE BANK', 'entry' => 'VERDANT MICROFINANCE BANK', 'code' => '090474', 'nip' => '090474'),
        array('name' => 'VFD Micro Finance Bank', 'entry' => 'VFD', 'code' => '566', 'nip' => '090110'),
        array('name' => 'VFD Micro Finance Bank', 'entry' => 'VFD MFB', 'code' => '566', 'nip' => '090110'),
        array('name' => 'VFD Micro Finance Bank', 'entry' => 'VFD Micro Finance Bank', 'code' => '566', 'nip' => '090110'),
        array('name' => 'VISUAL ICT', 'entry' => 'VISUAL ICT', 'code' => '100023', 'nip' => '100023'),
        array('name' => 'VTNetworks', 'entry' => 'VTNETWORK', 'code' => '100012', 'nip' => '100012'),
        array('name' => 'VTNetworks', 'entry' => 'VTNetworks', 'code' => '100012', 'nip' => '100012'),
        array('name' => 'Verite Microfinance Bank', 'entry' => 'Verite Microfinance Bank', 'code' => '090123', 'nip' => '090123'),
        array('name' => 'Virtue Microfinance Bank', 'entry' => 'Virtue Microfinance Bank', 'code' => '090150', 'nip' => '090150'),
        array('name' => 'Visa Microfinance Bank', 'entry' => 'Visa Microfinance Bank', 'code' => '090139', 'nip' => '090139'),
        array('name' => 'Wema Bank', 'entry' => 'WEMA BANK', 'code' => '035', 'nip' => '000017'),
        array('name' => 'Wema Bank', 'entry' => 'Wema Bank', 'code' => '035', 'nip' => '000017'),
        array('name' => 'Wema Bank', 'entry' => 'Wema Bank PLC', 'code' => '035', 'nip' => '000017'),
        array('name' => 'Wetland Microfinance Bank', 'entry' => 'Wetland Microfinance Bank', 'code' => '090120', 'nip' => '090120'),
        array('name' => 'Winview Microfinance Bank', 'entry' => 'Winview Microfinance Bank', 'code' => '090419', 'nip' => '090419'),
        array('name' => 'Xslnce Microfinance Bank', 'entry' => 'Xslnce Microfinance Bank', 'code' => '090124', 'nip' => '090124'),
        array('name' => 'YCT Microfinance Bank', 'entry' => 'YCT Microfinance Bank', 'code' => '090466', 'nip' => '090466'),
        array('name' => 'Yes Microfinance Bank', 'entry' => 'Yes Microfinance Bank', 'code' => '090142', 'nip' => '090142'),
        array('name' => 'Yes Microfinance Bank', 'entry' => 'YES MICROFINANCE BANK', 'code' => '090142', 'nip' => '090142'),
        array('name' => 'YOBE MICROFINANCE BANK', 'entry' => 'YOBE MICROFINANCE BANK', 'code' => '090252', 'nip' => '090252'),
        array('name' => 'Zenith Bank', 'entry' => 'Zenith Bank', 'code' => '057', 'nip' => '000015'),
        array('name' => 'Zenith Bank', 'entry' => 'Zenith bank PLC', 'code' => '057', 'nip' => '000015'),
        array('name' => 'Zenith Bank', 'entry' => 'ZENITH BANK', 'code' => '057', 'nip' => '000015'),
        array('name' => 'ZENITH EAZY WALLET', 'entry' => 'ZENITH EAZY WALLET', 'code' => '100034', 'nip' => '100034'),
        array('name' => 'ZenithMobile', 'entry' => 'ZenithMobile', 'code' => '100018', 'nip' => '100018'),
        array('name' => 'ZenithMobile', 'entry' => 'ZENITH MOBILE', 'code' => '100018', 'nip' => '100018'),
        array('name' => 'Zinternet Nigera Limited', 'entry' => 'ZINTERNET NIGERA LIMITED', 'code' => '100025', 'nip' => '100025'),
        array('name' => 'Zinternet Nigera Limited', 'entry' => 'Zinternet Nigera Limited', 'code' => '100025', 'nip' => '100025'),
        array('name' => 'e-Barcs Microfinance Bank', 'entry' => 'e-Barcs Microfinance Bank', 'code' => '090156', 'nip' => '090156'),
        array('name' => 'zikora mfb', 'entry' => 'zikora mfb', 'code' => '090504', 'nip' => '090504' )
    );
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $banks = Bank::distinct('name')->get(['name', 'code', 'nip']);
        return response([
            'status' => 'success',
            'message' => 'Banks fetched successfully',
            'data' => $banks
        ], 200);
    }

    public function bank_setup(){
        foreach($this->banks as $bank){
            $found = Bank::where('possible_entry', $bank['entry']);
            if($found->count() < 1){
                Bank::create([
                    'possible_entry' => $bank['entry'],
                    'name' => $bank['name'],
                    'code' => $bank['code'],
                    'nip' => $bank['nip']
                ]);
            }
        }
    }
}
